apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: mapreduce
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin-secret   # Change before production
  KC_DB:                   postgres
  KC_DB_URL:               jdbc:postgresql://postgres:5432/mapreduce
  KC_DB_USERNAME:          mapreduce
  KC_DB_PASSWORD:          mapreduce-secret
