apiVersion: v1
kind: Secret
metadata:
  name: manager-secret
  namespace: mapreduce
type: Opaque
stringData:
  DB_USER:         mapreduce
  DB_PASSWORD:     mapreduce-secret
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin-secret
