apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: mapreduce
data:
  MANAGER_BASE_URL:     http://manager-service:8081
  KEYCLOAK_ISSUER_URI:  http://keycloak:8080/realms/mapreduce
  KEYCLOAK_ADMIN_URL:   http://keycloak:8080
  KEYCLOAK_REALM:       mapreduce
  KEYCLOAK_CLIENT_ID:   mapreduce-cli
