apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mapreduce
type: Opaque
stringData:
  POSTGRES_DB:       mapreduce
  POSTGRES_USER:     mapreduce
  POSTGRES_PASSWORD: mapreduce-secret   #if we use this fr we are doomed
